# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True)),
                ('content', models.SlugField(default='', max_length=250, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=True, verbose_name='Publish to Web?')),
            ],
            options={
                'ordering': ['-updated'],
                'verbose_name': 'Biography',
                'verbose_name_plural': 'Biographies',
            },
        ),
    ]
