# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='content',
            field=models.TextField(),
        ),
    ]
